name: Question
description: Ask a question about Catspeak
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create this issue. If you need more immediate response times, get in contact on [Discord](https://discord.com/channels/724320164371497020/1007968808926982184).
  - type: textarea
    id: question
    attributes:
      label: What's your question?
      placeholder: Would the people who write mods in Catspeak be considered Nekomancers?
    validations:
      required: true
  - type: markdown
    attributes:
      value: "**`(.@ w @.) b  <(Thanks!)`**"
